### PR TITLE
Bugfix/3340/heroku deploy

### LINKED ISSUE #3340: heroku deploy not happening
When running refinerycms myapp --heroku, all the gems get installed, but when it attempts to find the heroku toolchain, it doesn't think that it is installed, even though it shows this in the backtrace:

>== 20180129204362 RenameTablesToNewNamespace: migrated (0.0324s) ==============
>
>heroku-cli/6.15.18-fdf2097 (linux-x64) node-v9.4.0
>/var/lib/gems/2.3.0/gems/refinerycms-core-4.0.1/lib/generators/refinery/cms/cms_generator.rb:145:in `deploy_to_hosting?':   [ABORTING] Heroku Toolbelt is not installed. Please re-start the installer after installing at: (RuntimeError)
>https://devcenter.heroku.com/articles/heroku-command-line

As you can see, heroku --version is being executed, and is present, but the method that checks for it, is checking !!system("heroku --version"), when I run it in irb, it is showing that system() is returning true, so I don't understand why this isn't working.....

### PR DESCRIPTION
**Pull request by bricesanchez**
This will fix #3340

### CODE REVIEW

File: core/lib/generators/refinery/cms/cms_generator.rb [hunk 1]
```diff
@@ -93,6 +94,10 @@ def append_heroku_gems!
 }.sub("{{production_gems}}", production_gems.join("\n  "))
     end
 
+    def current_ruby_version
+      (env_ruby_version = ENV['RUBY_VERSION']).present? ? env_ruby_version : RUBY_VERSION
```
Comment (parndt) [inline core/lib/generators/refinery/cms/cms_generator.rb]: for this you can use:
```ruby
def current_ruby_version
  ENV['RUBY_VERSION'].presence || RUBY_VERSION
end
```

Comment (bricesanchez) [reply core/lib/generators/refinery/cms/cms_generator.rb]: Your right i under use `.presence`, my bad! it's fixed now
